# Generated by Django 4.0.4 on 2022-05-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabeza',
            fields=[
                ('idcabeza', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cabeza',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('idcalificaciones', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'calificaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.AutoField(db_column='idCategoria', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.TextField()),
                ('imageulr', models.TextField(blank=True, null=True)),
                ('categoriaid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('idcomentarios', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'comentarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('idcotizacion', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cotizacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuerpo',
            fields=[
                ('idcuerpo', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cuerpo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('iddepartamentos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'departamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('identradas', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'entradas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('idcardex', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'kardex',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('idmunicipios', models.IntegerField(db_column='idMunicipios', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('municipiosid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'municipios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('idperfil', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'perfil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id_personas', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('telefono_celular', models.BigIntegerField()),
                ('correo_principal', models.CharField(db_column='Correo_principal', max_length=45)),
                ('correo_secundario', models.CharField(blank=True, db_column='Correo_secundario', max_length=45, null=True)),
                ('lugar_residencia', models.CharField(blank=True, max_length=45, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=45, null=True)),
                ('numero_identificacion', models.BigIntegerField()),
                ('fecha_de_expedicion', models.DateField()),
                ('edad', models.IntegerField()),
                ('personasid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(max_length=45)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('productoid', models.IntegerField(blank=True, null=True)),
                ('imagenurl', models.TextField(db_column='imagenUrl')),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idreserva', models.AutoField(primary_key=True, serialize=False)),
                ('tiempo', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salidas',
            fields=[
                ('idsalidas', models.AutoField(db_column='idSalidas', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'salidas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('idsubcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'subcategoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDeDocumento',
            fields=[
                ('idtipo_de_documento', models.IntegerField(db_column='idTipo_de_documento', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tipo_de_documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('idtipo_persona', models.AutoField(db_column='idTipo_Persona', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
            ],
            options={
                'db_table': 'tipo_persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UbicacionProducto',
            fields=[
                ('idubicacion_producto', models.AutoField(db_column='idUbicacion_producto', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ubicacion_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(max_length=32)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
