# Generated by Django 4.0.4 on 2022-05-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_delete_admininterfacetheme_delete_authgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeDocumento',
            fields=[
                ('idtipo_de_documento', models.IntegerField(db_column='idTipo_de_documento', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tipo_de_documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('idtipo_persona', models.AutoField(db_column='idTipo_Persona', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
            ],
            options={
                'db_table': 'tipo_persona',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='TipoDocumento',
        ),
        migrations.DeleteModel(
            name='TipoPersonas',
        ),
    ]
