# Generated by Django 4.0.4 on 2022-05-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInterfaceTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('active', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('title_visible', models.IntegerField()),
                ('logo', models.CharField(max_length=100)),
                ('logo_visible', models.IntegerField()),
                ('css_header_background_color', models.CharField(max_length=10)),
                ('title_color', models.CharField(max_length=10)),
                ('css_header_text_color', models.CharField(max_length=10)),
                ('css_header_link_color', models.CharField(max_length=10)),
                ('css_header_link_hover_color', models.CharField(max_length=10)),
                ('css_module_background_color', models.CharField(max_length=10)),
                ('css_module_text_color', models.CharField(max_length=10)),
                ('css_module_link_color', models.CharField(max_length=10)),
                ('css_module_link_hover_color', models.CharField(max_length=10)),
                ('css_module_rounded_corners', models.IntegerField()),
                ('css_generic_link_color', models.CharField(max_length=10)),
                ('css_generic_link_hover_color', models.CharField(max_length=10)),
                ('css_save_button_background_color', models.CharField(max_length=10)),
                ('css_save_button_background_hover_color', models.CharField(max_length=10)),
                ('css_save_button_text_color', models.CharField(max_length=10)),
                ('css_delete_button_background_color', models.CharField(max_length=10)),
                ('css_delete_button_background_hover_color', models.CharField(max_length=10)),
                ('css_delete_button_text_color', models.CharField(max_length=10)),
                ('list_filter_dropdown', models.IntegerField()),
                ('related_modal_active', models.IntegerField()),
                ('related_modal_background_color', models.CharField(max_length=10)),
                ('related_modal_rounded_corners', models.IntegerField()),
                ('logo_color', models.CharField(max_length=10)),
                ('recent_actions_visible', models.IntegerField()),
                ('favicon', models.CharField(max_length=100)),
                ('related_modal_background_opacity', models.CharField(max_length=5)),
                ('env_name', models.CharField(max_length=50)),
                ('env_visible_in_header', models.IntegerField()),
                ('env_color', models.CharField(max_length=10)),
                ('env_visible_in_favicon', models.IntegerField()),
                ('related_modal_close_button_visible', models.IntegerField()),
                ('language_chooser_active', models.IntegerField()),
                ('language_chooser_display', models.CharField(max_length=10)),
                ('list_filter_sticky', models.IntegerField()),
                ('form_pagination_sticky', models.IntegerField()),
                ('form_submit_sticky', models.IntegerField()),
                ('css_module_background_selected_color', models.CharField(max_length=10)),
                ('css_module_link_selected_color', models.CharField(max_length=10)),
                ('logo_max_height', models.PositiveSmallIntegerField()),
                ('logo_max_width', models.PositiveSmallIntegerField()),
                ('foldable_apps', models.IntegerField()),
            ],
            options={
                'db_table': 'admin_interface_theme',
                'managed': False,
            },
        ),
    ]
