# Generated by Django 4.0.4 on 2022-05-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_admininterfacetheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('idperfil', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'perfil',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
