# Generated by Django 4.0.4 on 2022-05-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_alter_producto_imagen_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
