# Generated by Django 4.0.4 on 2022-06-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_perfil_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
