# Generated by Django 4.0.4 on 2022-06-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0015_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='image',
            field=models.ImageField(default='tomates.jpg', upload_to=''),
        ),
    ]
