# Generated by Django 4.0.4 on 2022-06-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0016_perfil_descripcion_alter_perfil_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
