# Generated by Django 4.0.4 on 2022-06-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0017_alter_perfil_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.ImageField(default='fruit.jfif', upload_to=''),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='image',
            field=models.ImageField(default='perfil.jfif', upload_to=''),
        ),
    ]
