# Generated by Django 4.0.4 on 2022-06-06 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0021_contacto_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='formper',
        ),
    ]
