# Generated by Django 4.0.4 on 2022-06-15 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0022_remove_contacto_formper'),
    ]

    operations = [
        migrations.CreateModel(
            name='calificacionesuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='califi', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='califi_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='calificacionesuser',
            index=models.Index(fields=['from_user', 'to_user'], name='principal_c_from_us_5622a3_idx'),
        ),
    ]
