# Generated by Django 4.0.4 on 2022-06-16 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0023_calificacionesuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='seguidores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='califi', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='califi_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='calificacionesuser',
        ),
        migrations.AddIndex(
            model_name='seguidores',
            index=models.Index(fields=['from_user', 'to_user'], name='principal_s_from_us_c4f149_idx'),
        ),
    ]
