# Generated by Django 4.0.4 on 2022-06-16 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0024_seguidores_delete_calificacionesuser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': False, 'verbose_name': 'categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['id'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='principal.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
