# Generated by Django 4.0.4 on 2022-06-18 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0028_alter_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='slug',
        ),
    ]
