# Generated by Django 4.0.4 on 2022-06-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0029_remove_producto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
