# Generated by Django 4.0.4 on 2022-06-18 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0030_producto_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-id'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
