# Generated by Django 4.0.4 on 2022-06-18 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0031_alter_producto_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='slug',
        ),
    ]
