# Generated by Django 4.0.4 on 2022-06-18 14:26

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0033_producto_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nombre')),
                ('descripcion', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categoria',
            },
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productoscat', to='principal.categorias'),
        ),
    ]
