# Generated by Django 4.0.4 on 2022-06-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0035_alter_producto_categoria_delete_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Informacion_de_produccion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
