# Generated by Django 4.0.4 on 2022-06-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0036_producto_informacion_de_produccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
    ]
